#!/bin/bash

IP_RANGE="192.168.0."
MASTER_IP_LIST="187"
SLAVE_IP_LIST="185 186 246"
PUBLIC_IP_LIST="182"
Password=kbsys1234
bootstrap_ip="192.168.0.123:80"

for Node_ip in ${MASTER_IP_LIST}
do
        echo ${Node_ip}
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} curl -O http://${bootstrap_ip}/dcos_install.sh
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} bash /tmp/dcos_install.sh master>/tmp/install${Node_ip}.log 2>&1&
        echo install master started
done

for Node_ip in ${SLAVE_IP_LIST}
do
        echo ${Node_ip}
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} curl -O http://${bootstrap_ip}/dcos_install.sh
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} bash /tmp/dcos_install.sh slave>/tmp/install${Node_ip}.log 2>&1&
done

for Node_ip in ${PUBLIC_IP_LIST}
do
        echo ${Node_ip}
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} curl -O http://${bootstrap_ip}/dcos_install.sh
        sshpass -p ${Password} ssh -oStrictHostKeyChecking=no root@${IP_RANG}${Node_ip} bash /tmp/dcos_install.sh slave_public>/tmp/install.log 2>&1&
done
